#example yaml for fdir rules 
#First example show only token that can be parsed
add:
 - soft_id : 1
   port : 0
   input : 
     - flow_type : RTE_ETH_FLOW_NONFRAG_IPV4_OTHER
       flow :
         - ip4_flow :
             - ip4_src_ip : 1.0.0.0
               ip4_dst_ip : 0.0.0.0
       flow_ext :
         - vlan_tci : 0
   action : 
     - rx_queue : 0
       flex_off : 0
       behavior : RTE_ETH_FDIR_ACCEPT
       report_status : RTE_ETH_FDIR_REPORT_ID

add:
 - soft_id : 2
   port : 0
   input : 
     - flow_type : RTE_ETH_FLOW_NONFRAG_IPV4_OTHER
       flow :
         - ip4_flow :
             - ip4_src_ip : 0.0.0.0
               ip4_dst_ip : 0.0.0.0
       flow_ext :
         - vlan_tci : 0
   action : 
     - rx_queue : 1
       flex_off : 0
       behavior : RTE_ETH_FDIR_ACCEPT
       report_status : RTE_ETH_FDIR_REPORT_ID


